- name: Create certs directory
  file:
    path: ~/vault/certs
    state: directory
    mode: '0755'

- name: Copy certs
  copy:
    src: "../../certs-terraform/{{ item }}"
    dest: "~/vault/certs/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0444'
  with_items:
    - vault-ca-cert.pem
    - vault-node-cert.pem
    - vault-node-key.pem
    - vault-client-key.pem
    - vault-client-cert.pem
    - etcd-ca-cert.pem

- name: Copy docker-compose file    
  template:
    src: docker-compose.yml.j2
    dest: "~/vault/docker-compose.yml"

- name: Copy server.hcl file    
  template:
    src: server.hcl.j2
    dest: "~/vault/server.hcl"

- name: start container
  command: "docker-compose {{ item }}"
  args:
      chdir: "~/vault/"
  with_items:
    - down --remove-orphans
    - up -d