## Static configuration
[providers.docker]
[docker]
  network = "reverse-proxy"
  domain = "internal"
  exposeByDefault = false
[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.etcd]
    address = ":2379"
  [entryPoints.etcd-nodes]
    address = ":2380"
  [entryPoints.vault]
    address = ":8200"