---
- name: Generate Terraform Files 
  hosts: localhost
  vars:
    etcd:
      ca_common_name: etcd.private.vaultvnc.oraclevcn.com
      ca_organization_name: Binsabbar's Inc
      ca_dns_names: 
        - etcd.private.vaultvnc.oraclevcn.com
      clients:
        - name: etcd-node-1
          common_name: etcd-1.private.vaultvnc.oraclevcn.com
          dns_names:
            - etcd.private.vaultvnc.oraclevcn.com
            - etcd-1.private.vaultvnc.oraclevcn.com
        - name: etcd-node-2
          common_name: etcd-2.private.vaultvnc.oraclevcn.com
          dns_names:
            - etcd.private.vaultvnc.oraclevcn.com
            - etcd-2.private.vaultvnc.oraclevcn.com
        - name: etcd-node-3
          common_name: etcd-3.private.vaultvnc.oraclevcn.com
          dns_names:
            - etcd.private.vaultvnc.oraclevcn.com
            - etcd-3.private.vaultvnc.oraclevcn.com
        - name: vault-client
          common_name: vault.private.vaultvnc.oraclevcn.com
          dns_names:
            - vault.private.vaultvnc.oraclevcn.com
    vault:
      ca_common_name: vault.private.vaultvnc.oraclevcn.com
      ca_organization_name: Binsabbar's Inc
      ca_dns_names: 
        - vault.private.vaultvnc.oraclevcn.com
      clients:
        - name: vault-node
          common_name: vault.private.vaultvnc.oraclevcn.com
          dns_names:
            - vault.private.vaultvnc.oraclevcn.com
  roles:
    -  nodes-certs

- name: Generate Terraform Files 
  hosts: etcd_hosts
  vars:
    tcp_ports:
      - 2379
      - 2380
  roles:
    - firewall
    - deploy-etcd