version: "3.8"

services:
  etcd-3:
    image: quay.io/coreos/etcd:latest
    labels:
      # Cluster KV Service
      - "traefik.tcp.routers.etcd.service=etcd"
      - "traefik.tcp.services.etcd.loadbalancer.server.port=2379"
      - "traefik.tcp.routers.etcd.rule=HostSNI(`etcd.internal`)"
      - "traefik.tcp.routers.etcd.entrypoints=etcd"
      - "traefik.tcp.routers.etcd.tls.passthrough=true"
      - "traefik.tcp.routers.etcd.tls=true"
      # Node Service
      - "traefik.tcp.routers.etcd-node-3.service=etcd-node-3"
      - "traefik.tcp.services.etcd-node-3.loadbalancer.server.port=2380"
      - "traefik.tcp.routers.etcd-node-3.rule=HostSNI(`etcd-3.internal`)"
      - "traefik.tcp.routers.etcd-node-3.entrypoints=etcd-nodes"
      - "traefik.tcp.routers.etcd-node-3.tls.passthrough=true"
      - "traefik.tcp.routers.etcd-node-3.tls=true"
    volumes:
      - etcd-data-3:/etcd-data
      - ./certs/etcd-node-3-cert.pem:/certs/etcd-node-cert.pem
      - ./certs/etcd-node-3-key.pem:/certs/etcd-node-key.pem
      - ./certs/etcd-ca-cert.pem:/certs/etcd-ca-cert.pem
    expose:
      - 2379
      - 2380
    external_links: 
      - traefik:etcd-1.internal
      - traefik:etcd-2.internal
      - traefik:etcd-3.internal
    environment: 
      NODE_NAME: node3
      NODE_URL: etcd-3.internal
      CLUSTER_NODES: "node1=https://etcd-1.internal:2380,node2=https://etcd-2.internal:2380,node3=https://etcd-3.internal:2380"
      INITIAL_CLUSTER_TOKEN: etcd-vault-cluster
      CLIENT_URLS: etcd.internal
    entrypoint: sh 
    command:
      - -c 
      - > 
        /usr/local/bin/etcd
        --data-dir=/etcd-data
        --name=$$NODE_NAME
        --initial-cluster-token=$$INITIAL_CLUSTER_TOKEN
        --initial-cluster-state=new
        --initial-cluster=$$CLUSTER_NODES
        --advertise-client-urls=https://$$CLIENT_URLS:2379
        --listen-client-urls=https://0.0.0.0:2379
        --cert-file=/certs/etcd-node-cert.pem
        --key-file=/certs/etcd-node-key.pem
        --trusted-ca-file=/certs/etcd-ca-cert.pem
        --initial-advertise-peer-urls=https://$$NODE_URL:2380
        --listen-peer-urls=https://0.0.0.0:2380
        --peer-client-cert-auth 
        --peer-trusted-ca-file=/certs/etcd-ca-cert.pem
        --peer-cert-file=/certs/etcd-node-cert.pem
        --peer-key-file=/certs/etcd-node-key.pem

volumes:
    etcd-data-3:

networks:
  default:
    external:
      name: reverse-proxy