version: "3.8"

services:
  etcd-2:
    image: quay.io/coreos/etcd:latest
    labels:
      # Cluster KV Service
      - "traefik.tcp.routers.etcd.service=etcd"
      - "traefik.tcp.services.etcd.loadbalancer.server.port=2379"
      - "traefik.tcp.routers.etcd.rule=HostSNI(`etcd.internal`)"
      - "traefik.tcp.routers.etcd.entrypoints=etcd"
      - "traefik.tcp.routers.etcd.tls.passthrough=true"
      - "traefik.tcp.routers.etcd.tls=true"
      # Node Service
      - "traefik.http.routers.etcd-node-2.service=etcd-node-2"
      - "traefik.http.services.etcd-node-2.loadbalancer.server.port=2380"
      - "traefik.http.routers.etcd-node-2.rule=Host(`etcd-2.internal`)"
      - "traefik.http.routers.etcd-node-2.entrypoints=etcd-nodes"
      # - "traefik.tcp.routers.etcd-node-2.tls.passthrough=true"
      # - "traefik.tcp.routers.etcd-node-2.tls=true"
    volumes:
      - etcd-data-2:/etcd-data
      - ./certs/etcd-node-2-cert.pem:/certs/etcd-node-cert.pem
      - ./certs/etcd-node-2-key.pem:/certs/etcd-node-key.pem
      - ./certs/etcd-ca-cert.pem:/certs/etcd-ca-cert.pem
    expose:
      - 2379
      - 2380
    external_links: 
      - traefik:etcd-1.internal
      - traefik:etcd-2.internal
      - traefik:etcd-3.internal
    environment: 
      NODE_NAME: node2
      NODE_URL: etcd-2.internal
      CLUSTER_NODES: "node1=http://etcd-1.internal:2380,node2=http://etcd-2.internal:2380,node3=http://etcd-3.internal:2380"
      INITIAL_CLUSTER_TOKEN: etcd-vault-cluster
    entrypoint: sh 
    command:
      - -c 
      - > 
        /usr/local/bin/etcd
        --data-dir=/etcd-data
        --name=$$NODE_NAME
        --initial-cluster-token=$$INITIAL_CLUSTER_TOKEN
        --initial-cluster-state=new
        --initial-cluster=$$CLUSTER_NODES
        --initial-advertise-peer-urls=http://$$NODE_URL:2380
        --advertise-client-urls=http://etcd.internal:2379
        --listen-peer-urls=http://0.0.0.0:2380
        --listen-client-urls=https://0.0.0.0:2379
        --cert-file=/certs/etcd-node-cert.pem
        --key-file=/certs/etcd-node-key.pem
        --trusted-ca-file=/certs/etcd-ca-cert.pem

volumes:
  etcd-data-2:

networks:
  default:
    external:
      name: reverse-proxy