[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.etcd]
    address = ":2379"
  [entryPoints.etcd-nodes]
    address = ":2380"
  [entryPoints.vault]
    address = ":8200"
    
[providers.file]
    directory = "/etc/traefik"
    watch = true
    filename = "routes.yml"
    debugLogGeneratedTemplate = true